# Generated by Django 5.2.4 on 2025-07-05 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age_group', models.CharField(choices=[('<18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45+', '45+')], max_length=5)),
                ('dating_goal', models.CharField(choices=[('LTR', 'Long-term relationship'), ('STD', 'Short-term dating'), ('FRD', 'Friendship'), ('CAS', 'Casual')], max_length=3)),
                ('recent_dates', models.JSONField(blank=True, default=list, help_text='List of recent date activities or preferences', null=True)),
                ('rizz_styles', models.JSONField(default=dict, help_text='Preferred communication styles and preferences')),
                ('chat_platform', models.CharField(blank=True, choices=[('TD', 'Tinder'), ('IG', 'Instagram'), ('TI', 'TikTok'), ('WH', 'WhatsApp'), ('TE', 'Telegram'), ('OT', 'Other')], max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
