# Generated by Django 5.2.3 on 2025-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='recent_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of recent date activities or preferences', null=True),
        ),
    ]
