# Generated by Django 5.2.3 on 2025-07-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_preferences_recent_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='age_group',
            field=models.CharField(choices=[('<18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45+', '45+')], max_length=5),
        ),
    ]
